"use client"

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import { API_ENDPOINTS } from '@/src/lib/config';
import { Upload, FileText, CheckCircle, AlertCircle, ArrowLeft, Download, Gavel, Book } from 'lucide-react';
import Image from 'next/image';

interface Summary {
    document_overview: {
        title: string;
        type: string;
        parties: string;
        date: string;
    };
    core_arguments: string[];
    final_verdict: {
        decision: string;
        reasoning: string;
    };
    acts_cited: Array<{
        act: string;
        sections: string[];
        relevance: string;
    }>;
    key_timeline: Array<{
        date: string;
        event: string;
    }>;
    key_points: string[];
}

export default function SummarizePage() {
    const router = useRouter();
    const [file, setFile] = useState<File | null>(null);
    const [isDragging, setIsDragging] = useState(false);
    const [isUploading, setIsUploading] = useState(false);
    const [summary, setSummary] = useState<Summary | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [filename, setFilename] = useState<string>('');

    const handleDragOver = (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragging(true);
    };

    const handleDragLeave = () => {
        setIsDragging(false);
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragging(false);

        const droppedFile = e.dataTransfer.files[0];
        if (droppedFile && droppedFile.type === 'application/pdf') {
            setFile(droppedFile);
            setError(null);
        } else {
            setError('Please upload a PDF file');
        }
    };

    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        const selectedFile = e.target.files?.[0];
        if (selectedFile && selectedFile.type === 'application/pdf') {
            setFile(selectedFile);
            setError(null);
        } else {
            setError('Please upload a PDF file');
        }
    };

    const handleUpload = async () => {
        if (!file) return;

        setIsUploading(true);
        setError(null);

        const formData = new FormData();
        formData.append('file', file);

        try {
            const token = localStorage.getItem('token');
            const response = await axios.post(
                API_ENDPOINTS.summarize + '/upload',
                formData,
                {
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': 'multipart/form-data',
                    },
                }
            );

            setSummary(response.data.summary);
            setFilename(response.data.filename);
        } catch (err: any) {
            setError(err.response?.data?.detail || 'Failed to process PDF. Please try again.');
        } finally {
            setIsUploading(false);
        }
    };

    const downloadSummary = () => {
        if (!summary) return;

        const text = `
LEGAL DOCUMENT SUMMARY
Generated by SamvidhanAI

DOCUMENT OVERVIEW
Title: ${summary.document_overview.title}
Type: ${summary.document_overview.type}
Parties: ${summary.document_overview.parties}
Date: ${summary.document_overview.date}

CORE ARGUMENTS
${summary.core_arguments.map((arg, i) => `${i + 1}. ${arg}`).join('\n')}

FINAL VERDICT
Decision: ${summary.final_verdict.decision}
Reasoning: ${summary.final_verdict.reasoning}

ACTS & SECTIONS CITED
${summary.acts_cited.map(act => `
- ${act.act}
  Sections: ${act.sections.join(', ')}
  Relevance: ${act.relevance}
`).join('\n')}

KEY TIMELINE
${summary.key_timeline.map(item => `${item.date}: ${item.event}`).join('\n')}

KEY POINTS
${summary.key_points.map((point, i) => `${i + 1}. ${point}`).join('\n')}
        `.trim();

        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `summary-${filename.replace('.pdf', '')}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="min-h-screen px-2 bg-gradient-to-br from-zinc-50 to-zinc-100">
            <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10  sm:py-16 lg:py-14">
                <div className="mb-6 sm:mb-8">
                    <button
                        onClick={() => router.push('/dashboard')}
                        className="flex items-center gap-2 text-zinc-600 hover:text-zinc-900 mb-4 transition-colors text-sm sm:text-base cursor-pointer"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        Back to Dashboard
                    </button>
                    <div className="flex items-start gap-3 mb-2">
                        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-black text-white rounded-lg flex items-center justify-center flex-shrink-0">
                            <FileText className="w-5 h-5 sm:w-6 sm:h-6" />
                        </div>
                        <div>
                            <h1 className="text-2xl sm:text-3xl font-bold text-zinc-900">Legal Document Summarizer</h1>
                            <p className="text-sm sm:text-base text-zinc-600 mt-1">Upload a PDF to extract core arguments, verdict, and cited acts</p>
                        </div>
                    </div>
                </div>

                {!summary ? (
                    <div className="bg-white rounded-xl sm:rounded-2xl p-4 sm:p-6 lg:p-8">
                        <div
                            onDragOver={handleDragOver}
                            onDragLeave={handleDragLeave}
                            onDrop={handleDrop}
                            className={`border-2 border-dashed rounded-lg sm:rounded-xl p-8 sm:p-12 text-center transition-all ${isDragging
                                ? 'border-black bg-zinc-50'
                                : 'border-zinc-300 hover:border-zinc-400'
                                }`}
                        >
                            <Upload className={`w-12 h-12 sm:w-16 sm:h-16 mx-auto mb-4 ${isDragging ? 'text-black' : 'text-zinc-400'}`} />
                            <h3 className="text-lg sm:text-xl font-semibold text-zinc-900 mb-2 break-words px-2">
                                {file ? file.name : 'Drop your PDF here'}
                            </h3>
                            <p className="text-sm sm:text-base text-zinc-600 mb-4">
                                or click to browse (Max 10MB)
                            </p>
                            <input
                                type="file"
                                accept=".pdf"
                                onChange={handleFileSelect}
                                className="hidden"
                                id="file-upload"
                            />
                            <label
                                htmlFor="file-upload"
                                className="inline-block px-4 sm:px-6 py-2.5 sm:py-3 bg-black text-white rounded-lg hover:bg-zinc-800 cursor-pointer transition-colors text-sm sm:text-base"
                            >
                                Select PDF File
                            </label>
                        </div>

                        {error && (
                            <div className="mt-4 flex items-start gap-2 text-red-600 bg-red-50 p-3 sm:p-4 rounded-lg text-sm sm:text-base">
                                <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
                                <span>{error}</span>
                            </div>
                        )}

                        {file && !error && (
                            <div className="mt-4 sm:mt-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 sm:gap-4 bg-zinc-50 p-3 sm:p-4 rounded-lg">
                                <div className="flex items-start gap-3 min-w-0 flex-1">
                                    <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                                    <div className="min-w-0 flex-1">
                                        <p className="font-medium text-zinc-900 truncate text-sm sm:text-base">{file.name}</p>
                                        <p className="text-xs sm:text-sm  text-zinc-600">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
                                    </div>
                                </div>
                                <button
                                    onClick={handleUpload}
                                    disabled={isUploading}
                                    className="w-full sm:w-auto px-4 sm:px-6 py-2.5 sm:py-3 bg-black text-white rounded-lg hover:bg-zinc-800 disabled:bg-zinc-300 disabled:cursor-not-allowed transition-colors text-sm sm:text-base whitespace-nowrap"
                                >
                                    {isUploading ? 'Processing...' : 'Summarize Document'}
                                </button>
                            </div>
                        )}
                    </div>
                ) : (
                    <div className="space-y-4 sm:space-y-6">
                        <div className="bg-white rounded-xl sm:rounded-2xl shadow-lg p-4 sm:p-6">
                            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 sm:gap-4 mb-4">
                                <h2 className="text-xl sm:text-2xl font-bold text-zinc-900">Document Summary</h2>
                                <div className="flex gap-2 sm:gap-3">
                                    <button
                                        onClick={downloadSummary}
                                        className="flex items-center gap-2 px-3 sm:px-4 py-2 bg-zinc-100 text-zinc-900 rounded-lg hover:bg-zinc-200 transition-colors text-sm sm:text-base flex-1 sm:flex-initial justify-center"
                                    >
                                        <Download className="w-4 h-4" />
                                        <span className="hidden sm:inline">Download</span>
                                        <span className="sm:hidden">Save</span>
                                    </button>
                                    <button
                                        onClick={() => {
                                            setSummary(null);
                                            setFile(null);
                                        }}
                                        className="px-3 sm:px-4 py-2 bg-black text-white rounded-lg hover:bg-zinc-800 transition-colors text-sm sm:text-base flex-1 sm:flex-initial whitespace-nowrap"
                                    >
                                        New Document
                                    </button>
                                </div>
                            </div>
                            <p className="text-sm sm:text-base text-zinc-600 truncate">File: {filename}</p>
                        </div>

                        <div className="bg-white rounded-xl sm:rounded-2xl shadow-lg p-4 sm:p-6">
                            <div className="flex items-center gap-2 mb-4">
                                <Image src="/iconn.png" alt="Logo" width={20} height={20} className="rounded-full shadow-sm" />
                                <h3 className="text-lg sm:text-xl font-bold text-zinc-900">Document Overview</h3>
                            </div>
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                                <div>
                                    <p className="text-xs sm:text-sm text-zinc-600 mb-1">Title</p>
                                    <p className="font-medium text-zinc-900 text-sm sm:text-base break-words">{summary.document_overview.title}</p>
                                </div>
                                <div>
                                    <p className="text-xs sm:text-sm text-zinc-600 mb-1">Type</p>
                                    <p className="font-medium text-zinc-900 text-sm sm:text-base">{summary.document_overview.type}</p>
                                </div>
                                <div>
                                    <p className="text-xs sm:text-sm text-zinc-600 mb-1">Parties</p>
                                    <p className="font-medium text-zinc-900 text-sm sm:text-base break-words">{summary.document_overview.parties}</p>
                                </div>
                                <div>
                                    <p className="text-xs sm:text-sm text-zinc-600 mb-1">Date</p>
                                    <p className="font-medium text-zinc-900 text-sm sm:text-base">{summary.document_overview.date}</p>
                                </div>
                            </div>
                        </div>

                        <div className="bg-white rounded-xl sm:rounded-2xl shadow-lg p-4 sm:p-6">
                            <div className="flex items-center gap-2 mb-4">
                                <Gavel className="w-5 h-5 text-green-600 flex-shrink-0" />
                                <h3 className="text-lg sm:text-xl font-bold text-zinc-900">Core Arguments</h3>
                            </div>
                            <ul className="space-y-3">
                                {summary.core_arguments.map((arg, i) => (
                                    <li key={i} className="flex gap-2 sm:gap-3">
                                        <span className="flex-shrink-0 w-5 h-5 sm:w-6 sm:h-6 bg-green-100 text-green-700 rounded-full flex items-center justify-center text-xs sm:text-sm font-semibold mt-0.5">
                                            {i + 1}
                                        </span>
                                        <p className="text-zinc-700 leading-relaxed text-sm sm:text-base">{arg}</p>
                                    </li>
                                ))}
                            </ul>
                        </div>

                        <div className="bg-white rounded-xl sm:rounded-2xl shadow-lg p-4 sm:p-6">
                            <div className="flex items-center gap-2 mb-4">
                                <CheckCircle className="w-5 h-5 text-purple-600 flex-shrink-0" />
                                <h3 className="text-lg sm:text-xl font-bold text-zinc-900">Final Verdict</h3>
                            </div>
                            <div className="space-y-3">
                                <div>
                                    <p className="text-xs sm:text-sm text-zinc-600 mb-1">Decision</p>
                                    <p className="font-medium text-zinc-900 text-sm sm:text-base">{summary.final_verdict.decision}</p>
                                </div>
                                <div>
                                    <p className="text-xs sm:text-sm text-zinc-600 mb-1">Reasoning</p>
                                    <p className="text-zinc-700 leading-relaxed text-sm sm:text-base">{summary.final_verdict.reasoning}</p>
                                </div>
                            </div>
                        </div>

                        {summary.acts_cited.length > 0 && (
                            <div className="bg-white rounded-xl sm:rounded-2xl shadow-lg p-4 sm:p-6">
                                <div className="flex items-center gap-2 mb-4">
                                    <Book className="w-5 h-5 text-orange-600 flex-shrink-0" />
                                    <h3 className="text-lg sm:text-xl font-bold text-zinc-900">Acts & Sections Cited</h3>
                                </div>
                                <div className="space-y-4">
                                    {summary.acts_cited.map((act, i) => (
                                        <div key={i} className="border-l-4 border-orange-500 pl-3 sm:pl-4">
                                            <p className="font-semibold text-zinc-900 mb-1 text-sm sm:text-base">{act.act}</p>
                                            <p className="text-xs sm:text-sm text-zinc-600 mb-2">
                                                Sections: {act.sections.join(', ')}
                                            </p>
                                            <p className="text-zinc-700 text-sm sm:text-base">{act.relevance}</p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {summary.key_timeline.length > 0 && (
                            <div className="bg-white rounded-xl sm:rounded-2xl shadow-lg p-4 sm:p-6">
                                <h3 className="text-lg sm:text-xl font-bold text-zinc-900 mb-4">Key Timeline</h3>
                                <div className="space-y-3">
                                    {summary.key_timeline.map((item, i) => (
                                        <div key={i} className="flex flex-col sm:flex-row gap-2 sm:gap-4">
                                            <div className="flex-shrink-0 text-xs sm:text-sm font-medium text-zinc-600">
                                                {item.date}
                                            </div>
                                            <p className="text-zinc-700 text-sm sm:text-base">{item.event}</p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        <div className="bg-white rounded-xl sm:rounded-2xl shadow-lg p-4 sm:p-6">
                            <h3 className="text-lg sm:text-xl font-bold text-zinc-900 mb-4">Key Points</h3>
                            <ul className="space-y-2">
                                {summary.key_points.map((point, i) => (
                                    <li key={i} className="flex gap-2 sm:gap-3 text-zinc-700 text-sm sm:text-base">
                                        <span className="text-zinc-400 flex-shrink-0">•</span>
                                        <span>{point}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}